export enum EEnvKey {
  NODE_ENV = 'NODE_ENV',
  APP_NAME = 'APP_NAME',
  APP_DESCRIPTION = 'APP_DESCRIPTION',
  APP_GLOBAL_PREFIX = 'APP_GLOBAL_PREFIX',
  APP_SWAGGER_PATH = 'APP_SWAGGER_PATH',
  APP_DOCS_SCHEMA = 'APP_DOCS_SCHEMA',
  APP_VERSION = 'APP_VERSION',
  APP_HOST = 'APP_HOST',
  APP_PORT = 'APP_PORT',
  APP_BASE_URL = 'APP_BASE_URL',
  APP_HOST_NAME = 'APP_HOST_NAME',

  JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',

  GOOGLE_RECAPCHA_SECRET_KEY = 'GOOGLE_RECAPCHA_SECRET_KEY',
  VERIFICATION_URL = 'VERIFICATION_URL',

  AUTH_NONCE_EXPIRATION_MINUTES = 'AUTH_NONCE_EXPIRATION_MINUTES',
  LOG_LEVEL = 'INFO',

  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  DB_SYNC = 'DB_SYNC',
  DB_LOG = 'DB_LOG',
  DB_RETRY_ATTEMPT = 'DB_RETRY_ATTEMPT',
  DB_RETRY_DELAY = 'DB_RETRY_DELAY',
  DB_EXTRA = 'DB_EXTRA',
  DB_MAX_CONNECTIONS = 'DB_MAX_CONNECTIONS',
  DB_SSL_ENABLED = 'DB_SSL_ENABLED',
  DB_REJECT_UNAUTHORIZED = 'DB_REJECT_UNAUTHORIZED',
  DB_CA = 'DB_CA',
  DB_KEY = 'DB_KEY',
  DB_CERT = 'DB_CERT',
  DB_URL = 'DB_URL',

  ADMINER_PORT = 'ADMINER_PORT',

  REDIS_PORT = 'REDIS_PORT',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_DB = 'REDIS_DB',

  S3_ACCESS_KEY_ID = 'S3_ACCESS_KEY_ID',
  S3_SECRET_ACCESS_KEY = 'S3_SECRET_ACCESS_KEY',
  S3_BUCKET = 'S3_BUCKET',
  S3_REGION = 'S3_REGION',
  S3_PREVIEW_URL = 'S3_PREVIEW_URL',
  S3_URL = 'S3_URL',

  AUTH_PEPPER = 'AUTH_PEPPER',
  AUTH_SALT_ROUNDS = 'AUTH_SALT_ROUNDS',

  CRYPTO_SECRET_KEY = 'CRYPTO_SECRET_KEY',

  FIREBASE_SERVICE_ACCOUNT_PATH = 'FIREBASE_SERVICE_ACCOUNT_PATH',

  X_BASE_URL = 'X_BASE_URL',
  X_CLIENT_ID = 'X_CLIENT_ID',
  X_CLIENT_SECRET = 'X_CLIENT_SECRET',

  IS_WRITE_LOG = 'IS_WRITE_LOG',

  KAFKA_PROVIDER = 'KAFKA_PROVIDER',
  KAFKA_BROKERS = 'KAFKA_BROKERS',
  KAFKA_CLIENT_ID = 'KAFKA_CLIENT_ID',
  KAFKA_SSL = 'KAFKA_SSL',
  KAFKA_REGION = 'KAFKA_REGION',

  BLOCKFROST_API_URL = 'BLOCKFROST_API_URL',
  BLOCKFROST_API_KEY = 'BLOCKFROST_API_KEY',
}

export enum EEnvironment {
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
  TESTING = 'testing',
  STAGING = 'staging',
}
