name: Deploy develop
run-name: ${{ github.actor }} is deploying develop branch🚀
on:
  push:
    branches:
      - 'develop'
jobs:
  Deploy:
    runs-on: [rainpump-be-dev-217]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.19
        uses: actions/setup-node@v2
        with:
          node-version: 18.19

      - name: Set up test environment variables
        run: |
          echo "${{ vars.DEV_ENV }}" >> .env

      - name: Setup docker 
        run: |
          docker build . -t rainmakr-ai:1.0.0
          docker compose -f docker-compose-dev.yml up -d